### ISSUE TITLE
Is there a way to edit specific field on ra-data-hasura

### ISSUE THREAD

**Issue by leejh10003** [hasura/ra-data-hasura#1]
Hello, I'm developing dashboard for company with react-admin.

I want to update only the value user can changed. But for now, react-admin try to update all the values of a record(of course, it is the way it designed to).

I implemented in the way manually building the GraphQL query string but it seems so inefficient. Is there a way to update only the value user can change(doesn’t matter handling restriction in frontend or hasura ) or changed like https://github.com/marmelab/react-admin/issues/2414?

**Comment by zenflow** [comment]
@praveenweb Please check out my PR #27 for this :)

**Comment by leejh10003** [comment]
> @praveenweb Please check out my PR #27 for this :)

Lovely😍! And sorry about the late reply🙏
