### ISSUE TITLE
support jsonb ReferenceManyField target="a.b@_contains@c.d"

### ISSUE THREAD

**Issue by fkowal** [hasura/ra-data-hasura#104]
enable support for `_contains` operator and nested path in `jsonb` joins

**Comment by cpursley** [comment]
This looks useful @fkowal ~ if you don't mind, could you document it's usage in the README?

**Comment by fkowal** [comment]
i added a readme sample

and i also added a backward compatible change

to use the same standard / prefix for nested filters

`. -> #`

**Comment by fkowal** [comment]
changes merged thx
