### ISSUE TITLE
v1/query endpoint is for administrators only

### ISSUE THREAD

**Issue by webdeb** [hasura/ra-data-hasura#11]
Hello, just started to dive into it, and I eventually faced some sort of a problem with the design of this package.

In the Readme it says:

> serverEndpoint - The URL at which Hasura GraphQL Engine is running. (for example: http://localhost:8080). This is required. It should also expose /v1/query endpoint.

My problem is with the last line: **It should also expose /v1/query endpoint**

I am not sure, how official this package is, but the official hasura documentations says about this endpoint, that it is THE metadata / schema endpoint:

> The schema / metadata API provides the following features:
>
>* Execute SQL on the underlying Postgres database, supports schema modifying actions.
>* Modify Hasura metadata (permission rules and relationships).
>
>**This is primarily intended to be used as an admin API to manage the Hasura schema and metadata.**

Does it mean, that this package is for superadmins only? Because my intent was to provide an interface for moderators / translators / etc. I am not willing to open an superadmin endpoint for this purpose.

Please correct me, if I am wrong

**Comment by cchampou** [comment]
I'm glad you asked @webdeb, because i'm in the building process too, and didn't notice this detail. I'd like to use my application with lower permissions users too.

**Comment by webdeb** [comment]
I've tested it with a lower permission role "mod". The permissions are evaluated on the query layer, like any other hasura permissions. There are still problems with this package, for example all the previously fetched fields gets posted to the endpoint. Which may result in a situation when you can only allow edit a limited set of fields. https://github.com/hasura/ra-data-hasura/issues/1

Anyway, it seams not really clear to me, why we should use this package instead of `ra-data-graphql` which supports introspections, and fortunately hasura has good support for it. Hasura creates the correct introspection for your special role. _(I've not tested ra-data-graphql with hasura yet)_

@praveenweb Please correct me if I am missing some key benefits of ra-data-hasura compared to ra-data-graphql, I would just love to use the best suited technology for hasura, thank you!

**Comment by l-san** [comment]
Try this instead:

https://github.com/Steams/ra-data-hasura-graphql

**Comment by webdeb** [comment]
@l-san interesting, are you using it? What kind of a project?

**Comment by abumalick** [comment]
I tried this plugin with normal users (not super admin) and it is working well. If I don't add the permission to the user he cannot view or modify the data.
