### ISSUE TITLE
rewrite data provider using GraphQL API

### ISSUE THREAD

**Issue by praveenweb** [hasura/ra-data-hasura#13]
The current data provider is written using `/v1/query` JSON API which has a set of limitations (lack of support for remote schema, nested fields, querying functions for search etc).

A new data provider needs to be written supporting all the functionalities of Hasura and its grammar.

Reference - [ra-data-graphql](https://github.com/marmelab/react-admin/tree/master/packages/ra-data-graphql)

**Comment by cpursley** [comment]
There is some ongoing work in this direction with this package which utilizes ra-data-graphql: 

https://github.com/Steams/ra-data-hasura-graphql

**Comment by webdeb** [comment]
@praveenweb yes its definitely better to use the official graphql api, and I agree with @cpursley the **ra-data-hasura-graphql** project looks very promisingly. However it's a good starting point, and I think it would get even more attraction & contributions if it would be mentioned by the hasura team.

**Comment by praveenweb** [comment]
The steams/ra-data-hasura-graphql has been ported back to this repo with the release of [v0.1.0](https://github.com/hasura/ra-data-hasura/releases/tag/v0.1.0). The API remains the same from the `ra-data-hasura-graphql` library while the package name remains `ra-data-hasura` to cover the unified API of Hasura.

**Comment by sankalpmukim** [comment]
Guys is there any update on this issue and if this PR can get merged? #https://github.com/Steams/ra-data-hasura-graphql/pull/69
