### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by artistic-differences** [hasura/ra-data-hasura#132]
I have created a new application using vite  and when installing this component using

npm install --save graphql ra-data-hasura

I get the following issue reported 
(same issue when creating a new app with create react-app too)

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: graphql-ast-types-browser@1.0.2
npm WARN Found: graphql@16.6.0
npm WARN node_modules/graphql
npm WARN   graphql@"*" from the root project
npm WARN   1 more (ra-data-hasura)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^0.11.7" from graphql-ast-types-browser@1.0.2
npm WARN node_modules/graphql-ast-types-browser
npm WARN   graphql-ast-types-browser@"1.0.2" from ra-data-hasura@0.5.3
npm WARN   node_modules/ra-data-hasura
npm WARN 
npm WARN Conflicting peer dependency: graphql@0.11.7
npm WARN node_modules/graphql
npm WARN   peer graphql@"^0.11.7" from graphql-ast-types-browser@1.0.2
npm WARN   node_modules/graphql-ast-types-browser
npm WARN     graphql-ast-types-browser@"1.0.2" from ra-data-hasura@0.5.3
npm WARN     node_modules/ra-data-hasura
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: ra-data-graphql@4.4.3
npm WARN Found: graphql@16.6.0
npm WARN node_modules/graphql
npm WARN   graphql@"*" from the root project
npm WARN   1 more (ra-data-hasura)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer graphql@"^15.6.0" from ra-data-graphql@4.4.3
npm WARN node_modules/ra-data-graphql
npm WARN   ra-data-graphql@"^4.2.0" from ra-data-hasura@0.5.3
npm WARN   node_modules/ra-data-hasura
npm WARN 
npm WARN Conflicting peer dependency: graphql@15.8.0
npm WARN node_modules/graphql
npm WARN   peer graphql@"^15.6.0" from ra-data-graphql@4.4.3
npm WARN   node_modules/ra-data-graphql
npm WARN     ra-data-graphql@"^4.2.0" from ra-data-hasura@0.5.3
npm WARN     node_modules/ra-data-hasura

Any ideas how this can be resolved please ?

**Comment by arjunyel** [comment]
What version of node/npm are you using? I just tried it with Vite on StackBlitz and didn't get an error

**Comment by dvasdekis** [comment]
I got this as well with a fresh install of NPM (LTS) and Yarn.

**Comment by arjunyel** [comment]
I'll work on getting this fixed, in the meantime try adding graphql and this section to your package.json

https://github.com/hasura/ra-data-hasura/blob/fa52b44bfb7d617e768b60718a52d45ca79d5789/package.json#L57

**Comment by arjunyel** [comment]
@artistic-differences @dvasdekis did v0.5.4 fix it for you?
