### ISSUE TITLE
Overriding default primary key is not honored

### ISSUE THREAD

**Issue by ahmedrshdy** [hasura/ra-data-hasura#17]
I have created a pull request to fix it and honor config object configuration for primary key

**Comment by nbhargava** [comment]
There seem to be a couple places, where this isn't being respected. I've added #20 as another PR that handles some of the issues I've run into just walking through the react-admin tutorial (https://marmelab.com/react-admin/Tutorial.html).

**Comment by agent3bood** [comment]
I am having some issues when primary key is not "id".
I have finished the "list" view, on edit it is failing.
Please look into this issue, I am patching my own version for now and waiting for this to be closed.

related PRs 
https://github.com/hasura/ra-data-hasura/pull/20
https://github.com/hasura/ra-data-hasura/pull/16
Respect primary key on Order by
