### ISSUE TITLE
How can I customise the JWT network error response

### ISSUE THREAD

**Issue by bernardbaker** [hasura/ra-data-hasura#19]
I'm using React Admin. I have connected the Hasura data provider and I've implemented JWT. When I open the admin dashboard in a web browser and return to the page which was left open in Chrome after a good length of time I see a red notification appear with a message about JWT.

Refreshing the page removes the error and everything works as expected.

How can I customise this notification? How can I perform an action when this notification appears.

E.g. The notification appears and then fades away, after the fade has ended I would like to refresh the page.

**Comment by dvasdekis** [comment]
Hey @bernardbaker are you able to share your example react-admin JWT Hasura environment? I could help - it sounds like your JWT just needs a refresh. 

However I'm struggling to implement JWT in my own react-admin environment in a way Hasura is happy with! I'd love to know how you did it.

**Comment by bernardbaker** [comment]
@dvasdekis I'm not able to share my environment with you.

But I could help you to get your environment set up. What's your tech stack?

DB ?
DB Host platform?
JWT Authoritative Server that issues the tokens?

My intention is to be added as a collaborator to your project. Implement the solution. And provide guidance to you on how to get it set up where you otherwise wouldn't like to provide me with access.

How does that sound?

**Comment by dvasdekis** [comment]
@bernardbaker that's a very generous offer! Thank you!

[My tech stack is here](https://github.com/dvasdekis/react-admin-low-code/tree/ra-data-version). You can clone the repo, and run `docker-compose up --renew-anon-volumes --build` to start up the whole stack locally. It is set up for firebase auth through firebase SaaS, with a test user as `test@example.com` with password `bigpassword`. 

I am trying to get Hasura to accept the JWT that firebase produces, but I am having trouble getting the JWT into the header of the ra-data-hasura requests.

**Comment by bernardbaker** [comment]
Hi,

I'll take a look. I might not have to clone it. But rather look at the
hasura data provider implementation code section.

Can you send a link to the files that import the data provider and the file
which receives the token?

Regards,
Bernard

**Comment by bernardbaker** [comment]
Is your Hasura instance setup to use JWT?

Regards,

Bernard T. A. Baker

**Comment by bernardbaker** [comment]
Hi,

I looked at the code and you are *sending a token* to the Hasura instance.
But the token *doesn't contain the required Hasura headers [2]*. And the
Hasura instance isn't properly configured to use JWT for authentication
*[3]*.


Take a look at
https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#tl-dr

* [2] *And also
https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#the-spec
which
explains what is needed in your JWT. Which is provided from Firebase.

*[3] *You can find information on how to configure JWT mode in Hasura here
https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#configuring-jwt-mode

*[3] *You'll need to update
https://github.com/dvasdekis/react-admin-low-code/blob/master/docker-compose.yaml
. Adding HASURA_GRAPHQL_JWT_SECRET.

*[3] *An example of the JWK URL for Firebase is
https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
.

*[3]* An example of running Hasura with JWT enabled using environment
variables is here
https://hasura.io/docs/1.0/graphql/manual/auth/authentication/jwt.html#running-with-jwt
.



Regards,

Bernard T. A. Baker

**Comment by dvasdekis** [comment]
Thanks Bernard! [I got it all working in this repo.](https://github.com/dvasdekis/react-admin-hasura-firebase)
Hopefully others can use it too!

**Comment by bernardbaker** [comment]
Great! 🏋️

**Comment by arjunyel** [comment]
@bernardbaker hello friend, the recommendation I found online was to use the apollo error link functionality, does that work for your needs? Please comment and reopen this issue if it doesnt :) Thank you! https://stackoverflow.com/a/68981018/4717424
