### ISSUE TITLE
[ra-data-hasura] data provider fails on remote schema

### ISSUE THREAD

**Issue by mhiley** [hasura/ra-data-hasura#2]
Hasura version: v1.0.0-beta6
ra-data-hasura version: 0.0.7

I'm using ra-data-hasura as the dataProvider in react-admin and it is generally working well. However, it does not appear to be able to handle remote schemas. For example, trying to do something like the following (made up example for simplicity):

```
        (await dataProvider)(CREATE, 'thing', { 
            data: { 
                id: 1,
                name: "foo"
            }
        })
```

results in a request that looks like this:

```
{"type":"insert","args":{"table":{"name":"thing","schema":"public"},"objects": ...
```

The problem is that `thing` doesn't exist on the public schema and is not actually a Postgres table at all, but a Hasura remote schema, so it gives the error:

```
{"path":"$.args","error":"table \"thing\" does not exist","code":"not-exists"}
```

I also tried passing '.thing' (results in empty schema parameter in request) and 'remote.thing' (just a guess) and neither of those work either.

Is there a way to make ra-data-hasura work with Remote Schemas?

On a side note, it looks like ra-data-hasura is built on Hasura's JSON API via `/v1/query`, however to find documentation for those API request types[ I have to go back to v0.15 Hasura documentation](https://docs.platform.hasura.io/0.15/platform/manual/data/insert.html). Are these API operations (`/v1/query` select/insert/update/delete/count) deprecated? If so, what does that mean for the future usability of ra-data-hasura? Will it eventually need to be re-implemented on top of the graphql api?

Thanks for any help! 😄

**Comment by praveenweb** [comment]
With the release of [v0.1.0](https://github.com/hasura/ra-data-hasura/releases/tag/v0.1.0), this should be fixed. Closing this now.
