### ISSUE TITLE
Allowing for empty sort parameter

### ISSUE THREAD

**Issue by mihaildu** [hasura/ra-data-hasura#21]
Hello guys!

I was wondering if it would be possible to guard against empty sort parameter. This would help me in my edge case where I run custom data provider queries to get all the records and I don't want to worry about what field to put there. It seems a bit weird to put a random field since I don't care what you sort by. This change will not affect current use cases in my opinion. I can make a PR for this too.

**Comment by praveenweb** [comment]
This should be fixed in [v0.1.0](https://github.com/hasura/ra-data-hasura/releases/tag/v0.1.0). Closing this.
