### ISSUE TITLE
Error when connecting to Heroku

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [hasura/ra-data-hasura#25]
I deployed hasura to heroku using the ```deploy to heroku``` button. 
I have not setup any authentication
I have created a new table in hasura

When I run react-admin, I get the following error
{"path":"$.args[0].args.order_by[0]","error":"\"id\" does not exist","code":"not-exists"}

**Comment by dragos199993** [comment]
Hi, most probably your deployed Hasura does not have the correct table set as React admin expects.
Or another cause will be that there are not enough fields on your deploy environment. Maybe a field is missing. Anyway it's related to corrupt data and it's not Heroku related.

**Comment by praveenweb** [comment]
Hi @VinayaSathyanarayana - By default react-admin expects `id` to exist in the backend. The error occurs when your table doesn't have an `id` column. Also check out the latest release [v0.1.0](https://github.com/hasura/ra-data-hasura/releases/tag/v0.1.0) which should ideally fix this.
