### ISSUE TITLE
"x-hasura-admin-secret" isn't forwarded to remote schemas

### ISSUE THREAD

**Issue by opvasger** [hasura/ra-data-hasura#29]
I want to forward the `x-hasura-admin-secret` header when querying/mutating remote schemas from the Hasura-console. 

This is useful, as I have my remote graphql-endpoints check for the header, to ease administrative access.

It looks like you're intentionally filtering it out. Correct? Would you reconsider this?

**Comment by hgiasac** [comment]
GraphQL Engine already parsed `x-hasura-admin-secret` to `x-hasura-role: admin` header already. You just need to check `x-hasura-role` header. Multiple layers authentication isn't necessary

**Comment by opvasger** [comment]
@hgiasac  what you're describing, combined with `x-forwarded-for`-header validation? I suppose I can't trust `x-hasura-role` on its own, as anyone could set it?

**Comment by hgiasac** [comment]
@opvasger Is the remote schema is external or internal? If it is internal network, you don't need to worry.

If the remote schema is external, you can use firewall IP whitelist, or use another API key header. It is safer than using one admin secret. If you still want to use admin secret, just add another header key than, say `x-myapp-admin-secret`, and use forward header from client option.

![remote schema](https://hasura.io/docs/1.0/_images/add-remote-schemas-interface1.png)

**Comment by opvasger** [comment]
Yes, it´s an external schema - and I did choose to make another header as my workaround for this one, as I can see how it could be problematic to have a single admin-secret for everything.

I appreciate the explanation :heart:
