### ISSUE TITLE
Accessing a Computed Field in React-Admin and Hasura

### ISSUE THREAD

**Issue by osseonews** [hasura/ra-data-hasura#34]
Hasura has the ability to create computed fields. See here: https://hasura.io/docs/1.0/graphql/core/schema/computed-fields.html

What is the best method of accessing these fields for a specific table with React-Admin using ra-data-hasura? When using ListGuesser the computed fields are not exposed to react-admin. So how can they be displayed?

**Comment by arjunyel** [comment]
@osseonews @mulyoved hi friends are you still having this issue? Computed Fields should show up in the schema introspection so it should just work... If its not could you please comment/reopen this issue? Thanks!
