### ISSUE TITLE
new row creation seems to be broken in 0.0.8

### ISSUE THREAD

**Issue by hixus** [hasura/ra-data-hasura#36]
Seems that primary key is filtered out from data in convertDataRequestToHTTP but on CREATE type it is required. Also the filter checks DEFAULT_PRIMARY_KEY so it works if the primary key is something else than "id" but with "id" creation is broken.

**Comment by praveenweb** [comment]
@hixus - We have made a new release [v0.1.0](https://github.com/hasura/ra-data-hasura/releases/tag/v0.1.0) with a new API to support all GraphQL queries. Upgrading should fix this.
