### ISSUE TITLE
Please provide a documentation example for custom mutations

### ISSUE THREAD

**Issue by Kanabanarama** [hasura/ra-data-hasura#49]
I'm trying to use a custom mutation (with the intention to append nested entities later), but the dataprovider does some strange things to my query:
```
const UPDATE_PRODUCT = gql`
  mutation updateProduct($id: Int, $name: String!, $customer_id: Int, $created_at: date!) {
    update_products (
      where: {
        id: { _eq: $id }
      }
      _set: {
        name: $name
        customer_id: $customer_id
        created_at: $created_at
      }
    ) {
      returning {
        id
        name
        customer_id
        created_at
      }
    }
  }
`;
```
I tested this query in the GraphiQL tool and it executes without a problem.
The update request that is sent to hasura however looks like this:
```
mutation update_products($_set: products_set_input, $where: products_bool_exp!) {
  data: update_products(_set: $_set, where: $where) {
    returning {
      update_products(where: {id: {_eq: $id}}, _set: {name: $name, customer_id: $customer_id, created_at: $created_at}) {
        returning {
          id
          name
          customer_id
          created_at
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
}
```
And therefore throws the console error:

``` Error: GraphQL error: field "update_products" not found in type: 'products'```

I did not find any hints in the documentation why this could be happening. How would an appropriate mutation have to look like?
If this occurs because of naming convention magic it would be useful to have that documented.

**Comment by jbek7** [comment]
were you able to figure out this?

**Comment by martin-koenig** [comment]
I have managed to get it working by following the answer in this issue: [https://github.com/hasura/ra-data-hasura/issues/70](url)

**Comment by arjunyel** [comment]
@Kanabanarama hi friend, did @martin-koenig example help you? If not feel free to comment/reopen the issue, thank you!
