### ISSUE TITLE
New Recomended process to add authentication in Runtime

### ISSUE THREAD

**Issue by sytabaresa** [hasura/ra-data-hasura#62]
Hi, thank for this awesome data provider.

with this new version using Apollo Client. how we can change in runtime, the JWT token header (Authorization: 'Bearer ...') and notify the introspection internal logic of `ra-data-hasura` to make another request with the correct headers? This is important because the intronspection query is only done once, and if you try to get resources withour the correct credentials, the instrospection logic doesn't allow.

Thanks.

**Comment by sytabaresa** [comment]
as explained [here](https://github.com/marmelab/react-admin/issues/4830), currently the best solution is to import an `instrospection.json`  generated previously to bypass the introspection query. So the user can get the resources _before_ login.

**Comment by martin-koenig** [comment]
Do you maybe have an example on how to actually pass the `instrospection.json` to the Hasura data provider? Thanks in advance

**Comment by cver** [comment]
I can prevent instrospection query by the following steps
```sh
npx get-graphql-schema -j -h 'Authorization=Bearer <token>' https://example.com/v1/graphql >> ./src/schema.json
```
Open ./src/schema.json file and edit from
```json
{
  "__schema": {
    "queryType": ...,
    "mutationType": ...,
    ...
  }
}
```
to
```json
{
  "queryType": ...,
  "mutationType": ...,
  ...
}
```
Back to App.js and define
```javascript
import * as schema from './schema.json';
const dataProvider = await buildHasuraProvider({ client: apolloClient, introspection: {schema} });
```

But now I don't know how to prevent loading the first resource page at the beginning

**Comment by arjunyel** [comment]
@sytabaresa hi friend and other friends in the thread, this comment implies this should be fixed now https://github.com/marmelab/react-admin/issues/4830#issuecomment-933351359

Please comment here if this needs to be reopened :)
