### ISSUE TITLE
How to configure primary key?

### ISSUE THREAD

**Issue by sixsixtrample** [hasura/ra-data-hasura#66]
It looks like 0.2.0 changed the way that config options are handled? I have a table with 'region_id' as the primary key, but react admin forces the PK to be 'id'. 

Is there a way to configure the mapping on the data provider with 0.2.0?

**Comment by braytonstafford** [comment]
Any resolution to this?

**Comment by arjunyel** [comment]
Hi friends, I've added an example here: https://github.com/hasura/ra-data-hasura/pull/102
