### ISSUE TITLE
`distinct_on` support

### ISSUE THREAD

**Issue by bell-steven** [hasura/ra-data-hasura#67]
I have been trying to figure out how to get the `distinct_on` variable working.

I played around with customBuildFields and queries, but I have been coming up short. 

There is [this](https://stackoverflow.com/questions/61587351/fetching-only-distinct-data-from-table-using-hasura-graphql-data-provider-in-rea) answer on StackOverflow, which doesn't work. 

Has anyone ever come across this and got it working?

**Comment by bharatkashyap** [comment]
### Extend the default `buildVariables` function 

- Use the existing [`buildVariables.js`](https://github.com/hasura/ra-data-hasura/blob/master/src/buildVariables.js) and extend it like so:
```js
    // buildGetListVariables 
    // L24 
   const { customFilters = [] } = params;
     
    // ...
    /** Setting "distinct_on" to be the `filters` object attribute to be used inside RA
     * and setting to a `distinct_on` variable
     * and removing from the filter object
     */

    const distinctOnField = "distinct_on";
    const { distinct_on = "" } = filterObj;
    filterObj = omit(filterObj, [distinctOnField]);
    
    // ... 
    
    // L150 
     if (params.sort) {
      result["order_by"] = set(
        {},
        params.sort.field,
        params.sort.order.toLowerCase()
      );
    }
    
    // Add the "distinct_on" attribute to the result object
    if (distinct_on) {
      result["distinct_on"] = distinct_on;
    }

 ```
 
 - Use this to pass to your `buildHasuraProvider` 
 
 Here's the implementation - [`customVariables.js`](https://github.com/Samagra-Development/device-donation/blob/master/portal/components/react-admin/customHasura/customVariables.js) and [`app.js`](https://github.com/Samagra-Development/device-donation/blob/master/portal/components/react-admin/app.js#L29)

**Comment by bell-steven** [comment]
Thanks!

Would the maintainers be open to adding this to the library? I would be more than happy to open a PR.

**Comment by bharatkashyap** [comment]
@praveenweb: Adding `distinct_on` support to the library

**Comment by arjunyel** [comment]
@bell-steven hey friend, could you please open a PR with your distinct_on changes? Thank you so much!

**Comment by bell-steven** [comment]
@arjunyel The repo has changed quite a bit since those changes, will have to try and find the time to rebase.
