### ISSUE TITLE
How can I configure end-point or query?

### ISSUE THREAD

**Issue by robindesu** [hasura/ra-data-hasura#7]
My instance of Hasura just allow queries for the endpoint "/v1/graphql" (The "/v1/query" it's mean to be just for admin use ); 
How can I change or override the endpoint request to "/v1/graphql"?
Beside that, I need to make a query that selects the sub fields of a resource. So how can I add a query for a request like GET_LIST?

This is the query that I would like to apply:
 
query MyQuery {
  account_customers {
    customer_id
    email
    given_name
  }
}

**Comment by a613** [comment]
It doesn't look possible to configure those paths.

See https://github.com/hasura/ra-data-hasura/blob/master/src/index.js#L272 - the string is hardcoded.

**Comment by cpursley** [comment]
Is anyone aware of an adapter for react-admin that makes use of Hasura's graphQL format?

**Comment by robindesu** [comment]
@cpursley this provider worked to list the basic Hasura format. 
Pay attention if you have "id"  column attribute in your table, this is necessary.
But I stopped to use it because as @a613 said, is not open to making general GraphQL queries, also the search doesn't work.

**Comment by a613** [comment]
Search actually did "work" for me, but it is case-sensitive and does not work with substrings, so not too useful.

**Comment by webdeb** [comment]
Seams to be related #11

**Comment by praveenweb** [comment]
The data provider is written using Hasura's JSON API. There is a plan to rewrite the provider using graphql which will support the above query.

Meanwhile you can also use [ra-data-hasura-graphql](https://github.com/Steams/ra-data-hasura-graphql), a community initiative project with graphql support, thanks to @cpursley 

Tracking this as part of #13 and closing this.
