### ISSUE TITLE
Unable to filter nested relationship

### ISSUE THREAD

**Issue by gradisarjoze** [hasura/ra-data-hasura#74]
I'm having an issue understanding how nested filtering should work. I can not get it to work.

I have an entity `service` which has a relationship with `user`. One service has one user. 
I am attempting to filter services by users name on `services list`, using a TextInput filter with `source="user#first_name@_ilike"`. If I am not misunderstanding, this should build a query like:
```
...
user: {
  first_name: {
    _ilike: "%TEXT%"
  }
}
...
```

But this never gets built into the query. To my understanding because of the implementation below.
If code is split by `@` and the first part is used to find a field, we are looking for a `user#first_name` which doesn't exist and the whole filter appending process is skipped.
https://github.com/hasura/ra-data-hasura/blob/e0c0d4b06bd49260b882e64935bb17b8e4726777/src/buildVariables.js#L87-L90

Could anyone point me in the right direction if I am using this filter feature incorrectly entirely?

**Comment by arjunyel** [comment]
@gradisarjoze hi friend I tested and I believe this was fixed by https://github.com/hasura/ra-data-hasura/pull/76 and in 0.3.0

If you are still having this issue please comment here and Ill reopen and take another look, thank you!
