### ISSUE TITLE
Runtime error when building with Vite

### ISSUE THREAD

**Issue by techpet** [hasura/ra-data-hasura#83]
When using `vite build`, I get the following error:

```Uncaught (in promise) TypeError: ({get buildFields(){return Ce}, get buildMetaArgs(){return ue}, get buildArgs(){return ye}, get buildApolloArgs(){return Z}, get defaultBuildVariables(){return ee}, get defaultGetResponseParser(){return oe}, get buildQuery(){return H}, get buildGqlQuery(){return ce}, get buildVariables(){return ee}, default:(U,J={},re=ee,G=oe)=>{const te=at(at({},W),J),me=fe(re,be=>ce(be,te.buildFields,te.buildMetaArgs,te.buildArgs,te.buildApolloArgs,te.aggregateFieldName),G);return S(o()({},q,{buildQuery:me},U))}}) is not a function```

The dataProvider is defined with the following code:
```
defaultDataProvider = buildHasuraProvider(
{ client: apolloAuthClientWithAuth,
introspection: { schema: schema },
  });
```

tsconfig.json:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noImplicitAny": false,
    "jsx": "react-jsx"
  },
  "include": ["./src"]
}
```
vite.config.ts:
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()]
})
```

and the indicated firefox debugger erroneous build code:
![image](https://user-images.githubusercontent.com/1122529/159520486-dec5a9ad-0617-4050-8b2d-8a6414446b52.png)

Any ideas why this happens and how to fix that?

**Comment by arjunyel** [comment]
Hello friend, what version are you running? Make sure you're on 0.4.0

**Comment by techpet** [comment]
> Hello friend, what version are you running? Make sure you're on 0.4.0

Thank you very much @arjunyel! The new version solves this error. I was struggling for days!

With the new version how could one specify a stored schema.json for the introspection?
Format
```
defaultDataProvider = buildHasuraProvider(
{ client: apolloAuthClientWithAuth,
introspection: { schema: schema },
  });
```
doesn't seem to work for me anymore.

**Comment by arjunyel** [comment]
Im not sure how you import json with Vite, this has been working for me using create-react-app which uses webpack.  `npx get-graphql-schema http://localhost:8080/v1/graphql --json > src/schema.json`

```typescript
import schema from './schema.json';

...

defaultDataProvider = buildHasuraProvider(
{ client: apolloAuthClientWithAuth,
introspection: { schema: schema.__schema as any },
  });
```

You may need to add an extra `as any` until this lands https://github.com/marmelab/react-admin/pull/7638
